blank_issues_enabled: true
contact_links:
  - name: Report a bug with Z-Wave JS
    url: https://github.com/home-assistant/core/issues
    about: Please report issues with Z-Wave JS in the Home Assistant core repository unless a developer told you otherwise.
